version: '3'

services:
  emodjis:
    build:
      context: emodjis
      args:
        SERVER_URL: ${SERVER_URL}
        CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
        DB_ENGINE: ${DB_ENGINE}
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
    environment:
      - SERVER_URL=${SERVER_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - web-drv:/var/www
  nginx:
    build:
      context: nginx
    depends_on:
      - emodjis
    ports:
      - "80:80"
    volumes:
      - web-drv:/var/www
volumes:
  web-drv: