name: Test code

on: [push]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
    # You are now able to use PDM in your workflow
    - name: Install dependencies
      run: pdm install
    - name: Run project tests
      run: pdm run python manage.py test emodjis
      env:
          SERVER_URL: ${{ vars.SERVER_URL }}
          CORS_ALLOWED_ORIGINS: ${{vars.CORS_ALLOWED_ORIGINS}}
          CSRF_TRUSTED_ORIGINS: ${{vars.CSRF_TRUSTED_ORIGINS}}
          DB_ENGINE: ${{ vars.DB_ENGINE }}
          DB_NAME: ${{ vars.DB_NAME }}
          ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
          
          
