name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
    # You are now able to use PDM in your workflow
    - name: Install dependencies
      run: pdm install
    - name: Run project tests
        pdm run python manage.py test emodjis
